blogs/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
# from blogs import views
from .views import *

urlpatterns = [
	path('blogs/', blog_list, name='blog_list'),
	path('comments/', comment_list, name='comment_list'),
	path('comments/<id>/', comment_detail, name='comment_detail'), 
    path('blogs/<str:slug>/', blog_detail, name='blog_detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from profiles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
    path('', include('blogs.urls')),
    path('', include('users.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from profiles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.movie_list, name='movie_list'),
    path('me', views.my_profile, name='my_profile'),
    path('login_page', views.login_page, name='login_page'),
    path('logout_page', views.logout_page, name='logout_page'),
    path('/category/<id>', views.category, name='category'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
	path('users', views.users_request, name='users'),
]

blogs/models.py
from django.db import models
from profiles.models import Profile
from django.urls import reverse
from slugify import slugify
from ckeditor.fields import RichTextField



class Blog(models.Model):
	title = models.CharField(max_length=200)
	text = RichTextField(null=True)
	authors = models.ManyToManyField(Profile)
	slug = models.SlugField(null=True)

	def get_absolute_url(self):
		return reverse('blog_detail', kwargs={'slug':self.slug})

	def save(self, *args, **kwargs):
		self.slug=slugify(self.title)
		return super().save(*args, **kwargs)

	def __str__(self):
		return self.title


class Comment(models.Model):
	text = models.TextField()
	blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)

	def __str__(self):
		return self.text[:20]

	def get_absolute_url(self):
		return reverse('comment_detail', args=[str(self.id)])

	

profiles/models.py
from django.db import models
from django.contrib.auth.models import User

def movie_images_upload(instance, filename):
	return f"movie_{instance.movie.id}/{filename}"


def profile_image_upload(instance, filename):
	return f"profiles/{instance.id}/{filename}"


class Profile(models.Model):
	profile_photo = models.ImageField(upload_to=profile_image_upload)
	user =  models.OneToOneField(User, null=True, on_delete=models.CASCADE)
	name = models.CharField(max_length=60, null=True)
	phone_num = models.CharField(max_length=25, null=True)
	age = models.PositiveIntegerField()
	date_created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.name} {self.phone_num}"

	class Meta:
		ordering = ['-age']
		verbose_name='Профиль'
		verbose_name_plural='Профили'


class Category(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name


class Movie(models.Model):
	name = models.CharField(max_length=60, verbose_name='Название фильма')
	description = models.TextField(verbose_name='Краткий сюжет')
	release_date = models.DateField(verbose_name='Дата выхода')
	category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

	def __str__(self):
		return f"{self.name} {self.release_date}"


	class Meta:
		verbose_name='Фильм'
		verbose_name_plural='Фильмы'


class MovieImage(models.Model):
	file = models.ImageField(upload_to=movie_images_upload)
	movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

	def __str__(self):
		return self.file.url

	class Meta:
		verbose_name='Изображение к фильму'
		verbose_name_plural='Изображения к фильму'

users/models.py
from django.db import models

# Create your models here.

profiles/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = [
			"profile_photo",
			"name", 
			"phone_num",
			"age"
		]

users/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User 
		fields = ('username', 'email', 'password1', 'password2')

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

blogs/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog, Comment

def blog_list(request):
	blogs = Blog.objects.all().prefetch_related('comment_set')
	context = {
		'blogs': blogs
	}
	return render(request, 'blogs/blog_list.html', context)

def comment_list(request):
	comments = Comment.objects.all().select_related('blog')
	context = {
		'comments': comments
	}
	return render(request, 'blogs/comment_list.html', context)

def comment_detail(request, id):
	comment = get_object_or_404(Comment, id=id)
	context = {
		'comment': comment
	}
	return render(request, 'blogs/comment_detail.html', context)

def blog_detail(request, slug):
	blog = get_object_or_404(Blog, slug=slug)
	context = {
		'blog': blog
	}
	return render(request, 'blogs/blog_detail.html', context)

profiles/views.py
from django.shortcuts import render, redirect
from .models import Movie, Category
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

def movie_list(request):
	movies = Movie.objects.all()
	categories = Category.objects.all()
	context = {
		'movies': movies,
		'categories': categories
	}
	return render(request, 'profiles/movie_list.html', context)

@login_required(login_url='/login_page')
def my_profile(request):
	profile = request.user.profile
	context = {
		'profile': profile
	}
	return render(request, 'profiles/profile.html', context)


def login_page(request):
	""" Страница для входа """
	# для перекидывания аутентифицированного пользователя
	if request.user.is_authenticated:
		return redirect('my_profile')
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('my_profile')
	return render(request, 'profiles/login_page.html')

def logout_page(request):
	logout(request)
	return redirect('movie_list')


def category(request,id):
	category = get_object_or_404(Category, id=id)
	movies = category.movie_set.all()
	context = {
		'movies': movies
	}
	return render(request, 'profiles/category.html', context)

users/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from profiles.forms import ProfileForm
from django.contrib.auth import login 
from django.contrib import messages
from profiles import views

def users_request(request):
	if request.method == 'POST':
		reg_form = NewUserForm(request.POST)
		if reg_form.is_valid():
			user = reg_form.save()
			login(request, user)
			messages.success(request, 'Registration successful.')
			return redirect('movie_list')
		messages.error(request, 'Unsuccessful regisrtation. Invalid information.')
	reg_form = NewUserForm()
	profile_form = ProfileForm()
	context = {
		'reg_form': reg_form,
		'profile_form': profile_form
	}
	return render(request=request, template_name='users/users.html', context=context)

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link
	  rel="stylesheet"
	  href="https://unpkg.com/swiper@8/swiper-bundle.min.css"
	/>

	<script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">

</head>
<body>
	<div class="container">
		<header>
			{% if user.is_authenticated %}
				<a href="{% url 'logout_page' %}">Выход</a>
			{% else %}
				<a href="{% url 'login_page' %}">Вход</a>
			{% endif %}
		</header>
		{% block content %}

		{% endblock content %}
	</div>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/blogs/blog_detail.html
{% extends "_base.html" %}
{% load static %}
{% block content %}
<div>
	{{blog.title}}
	{{blog.text|safe}}
</div>
{% endblock content %}

templates/blogs/blog_list.html
{% extends "_base.html" %}
{% load static %}
{% block content %}
<div class="row">
	<h2>Пока</h2>

	<ul>
		{% for b in blogs %}
			<li>
					<a href="{{b.get_absolute_url}}">{{b.title}}</a>
					{% for c in b.comment_set.all %}
						<p>{{c.text}}</p>
					{% endfor %}
			</li>
		<hr>
		{% endfor %}
	</ul>

</div>
{% endblock content %}

templates/blogs/comment_detail.html
{% extends "_base.html" %}
{% load static %}
{% block content %}
<div>
	{{comment.text}}
</div>
{% endblock content %}

templates/blogs/comment_list.html
{% extends "_base.html" %}
{% load static %}
{% block content %}
<div class="row">
	<h2>Пока</h2>
	<ul>
		{% for c in comments %}
			<li>
					<a href="{{c.get_absolute_url}}">{{c.text}}</a>
				<p>
					{{c.blog.title}}
				</p>
			</li>
		<hr>
		{% endfor %}
	</ul>
</div>
{% endblock content %}

templates/profiles/category.html
{% extends '_base.html' %}

{% block content %}
{% for movie in movies %}
<div>
	{{movie}}
</div>
	
{% endfor %}
{% endblock content %}

templates/profiles/login_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
</head>
<body>
	<div class="container" style="height:100vh;">
		<div class="row" style="height:100vh;">
			<div class="d-flex justify-content-center form-container align-items-center">
				<form action="" method="POST">
					{% csrf_token %}
						<input type="text" name="username" placeholder="Ваш логин" class="form-control" />
						<input type="password" name="password" placeholder="Ваш пароль" class="form-control" />
			 			{#<input type="submit" name="Вход"> #}
						<button>Вход</button>
				</form>
			</div>
		</div>
	</div>
</body>
</html>

templates/profiles/movie_list.html
{% extends "_base.html" %}
{% load static %}
{% block content %}
<div class="row">
	<h2>Пока</h2>
	<div class="swiper">
	  <!-- Additional required wrapper -->
	  <div class="swiper-wrapper">
	    <!-- Slides -->
	    <div class="swiper-slide">Slide 1</div>
	    <div class="swiper-slide">Slide 2</div>
	    <div class="swiper-slide">Slide 3</div>
	    ...
	  </div>
	  <!-- If we need pagination -->
	  <div class="swiper-pagination"></div>

	  <!-- If we need navigation buttons -->
	  <div class="swiper-button-prev"></div>
	  <div class="swiper-button-next"></div>

	  <!-- If we need scrollbar -->
	  <div class="swiper-scrollbar"></div>
	</div>
	<ul>
		{% for c in categories %}
		<li>
			<a href="{% url 'category' c.id %}">{{c.name}}</a>
		</li>
		{% endfor %}
	</ul>
	<ul>
	{% for m in movies %}

		<li>
		{{m.name}}
				<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
				  <div class="carousel-inner">
					{% for image in m.movieimage_set.all %} 
						{% with forloop.counter0 as i %}
						    <div class="carousel-item {%if i is 0 %}active{% endif %}" ata-bs-interval="100">
					      		<img src="{{image.file.url}}" class="d-block w-100" alt="...">
					    	</div>
					    {% endwith %}
					{% endfor %}
				  </div>
				  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
				    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
				    <span class="visually-hidden">Previous</span>
				  </button>
				  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
				    <span class="carousel-control-next-icon" aria-hidden="true"></span>
				    <span class="visually-hidden">Next</span>
				  </button>
				</div>
{# 				<li><img class="movieimage" src="{{image.file.url}}"></li> #}
		</li>
	{% endfor %}
	</ul>
	<script>
	const swiper = new Swiper('.swiper', {
	  // Optional parameters
	  direction: 'vertical',
	  loop: true,

	  // If we need pagination
	  pagination: {
	    el: '.swiper-pagination',
	  },

	  // Navigation arrows
	  navigation: {
	    nextEl: '.swiper-button-next',
	    prevEl: '.swiper-button-prev',
	  },

	  // And if we need scrollbar
	  scrollbar: {
	    el: '.swiper-scrollbar',
	  },
	});
	</script>
</div>
{% endblock content %}

templates/profiles/profile.html
{% extends "_base.html" %}

{% block content %}
	<div class="row">
		<h3>{{profile.name}}</h3>
		<h4>username: {{user.username}}</h4>
		<img class="profile_picture" src="{{profile.profile_photo.url}}">
	</div>
{% endblock content %}

templates/users/users.html
{% extends "_base.html" %}
{% load static %}
{% block content %}

<h3>Register</h3>

<form method="POST" action="">
	{% csrf_token %}
	{{reg_form.as_p}}



	<input type="submit" name="Create User">
</form>
{% endblock content %}